# Generated by Django 4.2.5 on 2023-10-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demonstrator_Claims',
            new_name='Demonstrator_Claim',
        ),
    ]
