# Generated by Django 4.2.5 on 2023-10-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_demonstrator_claims_demonstrator_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demonstrator_claim',
            name='demonstrated_date',
            field=models.DateField(),
        ),
    ]
